# Generated by Django 5.0.3 on 2024-03-16 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Xomashyo',
                'verbose_name_plural': 'Xomashyolar',
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=255)),
                ('product_code', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitiy', models.IntegerField(default=0)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.materialmodel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.materialmodel')),
            ],
        ),
    ]
