# Generated by Django 5.0.3 on 2024-03-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousemodel',
            options={'verbose_name': 'Partiya', 'verbose_name_plural': 'Partiyalar'},
        ),
        migrations.AlterModelTable(
            name='warehousemodel',
            table='warehouse',
        ),
    ]
