# Generated by Django 5.0.3 on 2024-03-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_productmaterialmodel_quantitiy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaterialmodel',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
